/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => EasyViewPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  buttonSize: 13,
  showIncrementBtn: true,
  showDecrementBtn: true,
  showResetBtn: true,
  showThemeBtn: true,
  defaultFontSize: 18,
  showFocusBtn: true,
  showZenBtn: false,
  showReadingModeBtn: true,
  focusModeActive: false,
  zenModeActive: false,
  showNotifications: true,
  showRibbonIcon: true,
  ribbonAction: "toggle-theme"
};
var EasyViewPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.statusBarItem = null;
    this.themeBtn = null;
    this.ribbonIconEl = null;
    this.isReady = false;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new EasyViewSettingTab(this.app, this));
    this.registerCommands();
    this.restoreStates();
    this.refreshStatusBar();
    this.refreshRibbonIcon();
    this.registerEvent(this.app.workspace.on("css-change", () => {
      this.updateThemeIcon();
      if (this.settings.ribbonAction === "toggle-theme") this.refreshRibbonIcon();
    }));
    setTimeout(() => {
      this.isReady = true;
    }, 1e3);
  }
  onunload() {
    if (this.statusBarItem) this.statusBarItem.remove();
    document.body.classList.remove("easyview-focus-mode", "easyview-zen-mode");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.refreshStatusBar();
    this.refreshRibbonIcon();
  }
  notify(message, duration = 1500) {
    if (this.settings.showNotifications) {
      new import_obsidian.Notice(message, duration);
    }
  }
  registerCommands() {
    this.addCommand({ id: "toggle-focus-mode", name: "Toggle Focus Mode", callback: () => this.toggleFocusMode() });
    this.addCommand({ id: "toggle-zen-mode", name: "Toggle Zen Mode", callback: () => this.toggleZenMode() });
    this.addCommand({ id: "toggle-theme", name: "Toggle Theme", callback: () => this.toggleTheme() });
    this.addCommand({ id: "cycle-reading-mode", name: "Cycle Reading Mode", callback: () => this.cycleReadingMode() });
    this.addCommand({ id: "increase-font-size", name: "Increase Font Size", callback: () => this.adjustFontSize(1) });
    this.addCommand({ id: "decrease-font-size", name: "Decrease Font Size", callback: () => this.adjustFontSize(-1) });
    this.addCommand({ id: "reset-font-size", name: "Reset Font Size", callback: () => this.resetFontSize() });
  }
  restoreStates() {
    if (this.settings.focusModeActive) document.body.classList.add("easyview-focus-mode");
    if (this.settings.zenModeActive) document.body.classList.add("easyview-zen-mode");
  }
  refreshStatusBar() {
    if (this.statusBarItem) this.statusBarItem.empty();
    else this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.addClass("plugin-easyview", "easy-view-container-unique");
    this.statusBarItem.style.setProperty("--easy-view-btn-size", `${this.settings.buttonSize}px`);
    this.statusBarItem.oncontextmenu = (e) => {
      e.preventDefault();
      this.showContextMenu(e);
    };
    if (this.settings.showDecrementBtn) this.createBtn("minus", "Decrease", () => this.adjustFontSize(-1));
    if (this.settings.showIncrementBtn) this.createBtn("plus", "Increase", () => this.adjustFontSize(1));
    if (this.settings.showResetBtn) this.createBtn("rotate-ccw", "Reset", () => this.resetFontSize());
    if (this.settings.showReadingModeBtn) this.createBtn("book-open", "Mode", () => this.cycleReadingMode());
    if (this.settings.showFocusBtn) this.createBtn("maximize", "Focus", () => this.toggleFocusMode());
    if (this.settings.showZenBtn) this.createBtn("eye-off", "Zen", () => this.toggleZenMode());
    if (this.settings.showThemeBtn) {
      this.themeBtn = this.createBtn("sun", "Theme", () => this.toggleTheme());
      this.updateThemeIcon();
    }
  }
  createBtn(icon, title, onclick) {
    const b = this.statusBarItem.createEl("button", { cls: "easy-view-btn" });
    (0, import_obsidian.setIcon)(b, icon);
    b.title = title;
    b.onclick = onclick;
    return b;
  }
  showContextMenu(e) {
    const menu = new import_obsidian.Menu();
    menu.addItem((i) => i.setTitle(this.settings.focusModeActive ? "\u2713 Focus" : "Focus").setIcon("maximize").onClick(() => this.toggleFocusMode()));
    menu.addItem((i) => i.setTitle(this.settings.zenModeActive ? "\u2713 Zen" : "Zen").setIcon("eye-off").onClick(() => this.toggleZenMode()));
    menu.addSeparator();
    menu.addItem((i) => i.setTitle("Toggle Theme").setIcon("sun").onClick(() => this.toggleTheme()));
    menu.showAtMouseEvent(e);
  }
  adjustFontSize(change) {
    const currentSize = this.app.vault.getConfig("baseFontSize") || 16;
    let newSize = Math.min(Math.max(currentSize + change, 10), 30);
    this.app.vault.setConfig("baseFontSize", newSize);
    this.app.updateFontSize();
    this.notify(`Font size: ${newSize}px`);
  }
  resetFontSize() {
    this.app.vault.setConfig("baseFontSize", this.settings.defaultFontSize);
    this.app.updateFontSize();
    this.notify(`Font size reset to ${this.settings.defaultFontSize}px`);
  }
  toggleTheme() {
    const currentTheme = this.app.vault.getConfig("theme");
    const newTheme = currentTheme === "obsidian" ? "moonstone" : "obsidian";
    this.app.vault.setConfig("theme", newTheme);
    this.app.updateTheme();
    this.updateThemeIcon();
    if (this.settings.ribbonAction === "toggle-theme") this.refreshRibbonIcon();
    this.notify(`Theme: ${newTheme === "obsidian" ? "Dark" : "Light"}`);
  }
  updateThemeIcon() {
    if (!this.themeBtn) return;
    (0, import_obsidian.setIcon)(this.themeBtn, this.app.vault.getConfig("theme") === "obsidian" ? "moon" : "sun");
  }
  toggleFocusMode() {
    if (!this.settings.focusModeActive && this.settings.zenModeActive) {
      document.body.classList.remove("easyview-zen-mode");
      this.settings.zenModeActive = false;
    }
    const isActive = document.body.classList.toggle("easyview-focus-mode");
    this.settings.focusModeActive = isActive;
    this.saveSettings();
    this.notify(`Focus Mode: ${isActive ? "ON" : "OFF"}`);
  }
  toggleZenMode() {
    if (!this.settings.zenModeActive && this.settings.focusModeActive) {
      document.body.classList.remove("easyview-focus-mode");
      this.settings.focusModeActive = false;
    }
    const isActive = document.body.classList.toggle("easyview-zen-mode");
    this.settings.zenModeActive = isActive;
    this.saveSettings();
    this.notify(`Zen Mode: ${isActive ? "ON" : "OFF"}`);
  }
  cycleReadingMode() {
    var _a, _b;
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!view) return;
    const state = view.getState();
    let mode = state.mode === "source" && ((_a = state.source) != null ? _a : true) ? "source" : state.mode === "preview" ? "source" : "preview";
    let source = state.mode === "source" && ((_b = state.source) != null ? _b : true) ? false : state.mode === "preview" ? true : false;
    view.setState({ ...state, mode, source }, { history: false });
    this.notify(`Reading Mode: ${mode === "preview" ? "Reading" : "Editing"}`);
  }
  refreshRibbonIcon() {
    if (this.ribbonIconEl) {
      this.ribbonIconEl.remove();
      this.ribbonIconEl = null;
    }
    if (this.settings.showRibbonIcon && import_obsidian.Platform.isMobile) {
      let icon = "help-circle";
      let title = "EasyView";
      let action = () => {
      };
      switch (this.settings.ribbonAction) {
        case "toggle-theme":
          icon = this.app.vault.getConfig("theme") === "obsidian" ? "moon" : "sun";
          title = "Toggle Theme";
          action = () => this.toggleTheme();
          break;
        case "increase-font":
          icon = "plus";
          title = "Increase Font Size";
          action = () => this.adjustFontSize(1);
          break;
        case "decrease-font":
          icon = "minus";
          title = "Decrease Font Size";
          action = () => this.adjustFontSize(-1);
          break;
        case "reset-font":
          icon = "rotate-ccw";
          title = "Reset Font Size";
          action = () => this.resetFontSize();
          break;
        case "toggle-focus":
          icon = "maximize";
          title = "Toggle Focus Mode";
          action = () => this.toggleFocusMode();
          break;
        case "toggle-zen":
          icon = "eye-off";
          title = "Toggle Zen Mode";
          action = () => this.toggleZenMode();
          break;
        case "cycle-mode":
          icon = "book-open";
          title = "Cycle Reading Mode";
          action = () => this.cycleReadingMode();
          break;
      }
      this.ribbonIconEl = this.addRibbonIcon(icon, title, action);
    }
  }
};
var EasyViewSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Easy View Settings" });
    new import_obsidian.Setting(containerEl).setName("Button Size (px)").addSlider((s) => s.setLimits(10, 24, 1).setValue(this.plugin.settings.buttonSize).onChange(async (v) => {
      this.plugin.settings.buttonSize = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Default Font Size").addText((t) => t.setValue(String(this.plugin.settings.defaultFontSize)).onChange(async (v) => {
      const n = parseInt(v);
      if (!isNaN(n)) {
        this.plugin.settings.defaultFontSize = n;
        await this.plugin.saveSettings();
      }
    }));
    containerEl.createEl("h3", { text: "Mobile / Ribbon" });
    new import_obsidian.Setting(containerEl).setName("Show Ribbon Icon (Mobile Only)").setDesc("Display a shortcut icon on the mobile navigation bar. This setting is ignored on desktop.").addToggle((t) => t.setValue(this.plugin.settings.showRibbonIcon).onChange(async (v) => {
      this.plugin.settings.showRibbonIcon = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Ribbon Icon Action").setDesc("Select which feature the ribbon icon should trigger.").addDropdown((d) => d.addOption("toggle-theme", "Toggle Theme").addOption("increase-font", "Increase Font Size").addOption("decrease-font", "Decrease Font Size").addOption("reset-font", "Reset Font Size").addOption("toggle-focus", "Toggle Focus Mode").addOption("toggle-zen", "Toggle Zen Mode").addOption("cycle-mode", "Cycle Reading Mode").setValue(this.plugin.settings.ribbonAction).onChange(async (v) => {
      this.plugin.settings.ribbonAction = v;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Visibility" });
    new import_obsidian.Setting(containerEl).setName("Show Decrement").addToggle((t) => t.setValue(this.plugin.settings.showDecrementBtn).onChange(async (v) => {
      this.plugin.settings.showDecrementBtn = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Increment").addToggle((t) => t.setValue(this.plugin.settings.showIncrementBtn).onChange(async (v) => {
      this.plugin.settings.showIncrementBtn = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Reset").addToggle((t) => t.setValue(this.plugin.settings.showResetBtn).onChange(async (v) => {
      this.plugin.settings.showResetBtn = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Theme").addToggle((t) => t.setValue(this.plugin.settings.showThemeBtn).onChange(async (v) => {
      this.plugin.settings.showThemeBtn = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Focus").addToggle((t) => t.setValue(this.plugin.settings.showFocusBtn).onChange(async (v) => {
      this.plugin.settings.showFocusBtn = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show View Switcher").setDesc("Reader / Editing / Source").addToggle((t) => t.setValue(this.plugin.settings.showReadingModeBtn).onChange(async (v) => {
      this.plugin.settings.showReadingModeBtn = v;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Features" });
    new import_obsidian.Setting(containerEl).setName("Show Zen").addToggle((t) => t.setValue(this.plugin.settings.showZenBtn).onChange(async (v) => {
      this.plugin.settings.showZenBtn = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Action Tooltips").setDesc("Show a notification popup when an action (e.g., resizing font) is performed.").addToggle((t) => t.setValue(this.plugin.settings.showNotifications).onChange(async (v) => {
      this.plugin.settings.showNotifications = v;
      await this.plugin.saveSettings();
    }));
  }
};
